server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/googlevue?serverTimezone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

twilio:
  account:
    sid: YOUR_TWILIO_ACCOUNT_SID
  auth:
    token: YOUR_TWILIO_AUTH_TOKEN
  phone:
    number: YOUR_TWILIO_PHONE_NUMBER

